### ISSUE TITLE
RTD2660 Board not detected by i2cdetect -y 1

### ISSUE THREAD

**Issue by bhura112** [static-void/rtd266x_programmer#1]
i am connected RTD2660 Board with my PC and run your code for backup 
it's print I2C_ready
stuck on next step .......

**Comment by static-void** [comment]
If nothing is detected by i2cdetect it is possible there is something else wrong with your hardware setup, or maybe you've got the wrong I2C device. If neither of those is the issue, you can build with debug symbols and run with gdb to report back here where it gets stuck. To build with debug symbols run "make clean" and then "CPPFLAGS=-g make"

**Comment by bhura112** [comment]
Hello Sir,
            I am using ROVA Tools programmer software and FT232H programmer with RTD2660. 
            I get the following:
                                        Error: device didn’t send ack byte during FTDIUSBInterface::Read
            After this ,i am using ubuntu and install D2XX driver for FT232H. I2C working fine but my board not responding,When i send an ISP enable command.
            Now i am using PC vga port,When i connect my monitor with VGA  and run i2cdetect -y 1,it's show me random address.
             I already checked all communication lines SCL,SDA and Gnd everything in my Board. And also double checked all supply, VDD and ADC_VDD, PVCC everything in a correct manner. In my board : 
SCL1  ->> 58
SDA1 ->> 59
GND ->>GND
Serial Flash connected on 
     51,52,53,54 ...
Can you please tell me suggested errors?

**Comment by static-void** [comment]
What is the output from "i2cdetect -l"

**Comment by bhura112** [comment]
![myout](https://user-images.githubusercontent.com/16154752/30744131-5065522e-9fbe-11e7-8164-67600d74215a.png)

**Comment by static-void** [comment]
Well you have the correct interface. Have you tried a different VGA cable, as not all have the correct wiring apparently. I again suggest trying with gdb to see where it gets stuck

**Comment by bhura112** [comment]
at that point : 
                     I2C ready   
                     Attempting to read chip ID...
                     Write to 6F failed, keep trying...   /
                   .
                         .
                               .

**Comment by static-void** [comment]
The failure is when first attempting to speak to the flash IC over I2C, here: https://github.com/static-void/rtd266x_programmer/blob/master/i2clinux.cpp#L47

This suggests that either there is no flash IC present for the program to speak to, or the wiring is incorrect or flaky. Perhaps you should check the wiring of your VGA cable. Beyond that I don't know what to suggest (this is not a software problem).

**Comment by bhura112** [comment]
Thank you Sir
