### ISSUE TITLE
RTD2660 programmer Error

### ISSUE THREAD

**Issue by bhura112** [static-void/rtd266x_programmer#2]
https://github.com/static-void/rtd266x_programmer/blob/e83f32ed64ffeb678f95b5f80b9dd457fba01f28/main.cpp#L490
sir i am solved my hardware related error
now i am burning new .bin to rtd 
getting : error 
   **Jedec Id = 0xffffff
   Unknown Chip id**

**Comment by static-void** [comment]
If you're reading the ID as 0xffffff then there is probably still something wrong somewhere, as this looks like nothing actually responded with real data.

**Comment by bhura112** [comment]
Dear Bernard Black,
                             I am using S25FS-S Family serial flash. https://github.com/static-void/rtd266x_programmer/blob/e83f32ed64ffeb678f95b5f80b9dd457fba01f28/main.cpp#L19 but this SPI flash not listed in your program. Can you please tell me how can i add this device to list , i checked the datasheet some registers are differnet but maximum are same.

**Comment by bhura112** [comment]
http://www.mouser.com/ds/2/380/S25FS-S_00-271247.pdf
**page - 137**
i couldn't understand how can i read this device jedec Id 
can you please help me out?

**Comment by static-void** [comment]
According to page 79 of http://www.mouser.com/ds/2/380/S25FS-S_00-271247.pdf your device should respond to command `0x9F` (read ID command) with the information given in table 12.4.1. The jedec ID depends on the exact part number you are using, for example a 128Mb device should be `0x012018`. The whole entry for the `FlashDevices[]` array would be:

`{"S25FS128S" , 0x012018,      128 * 1024,       256, 64},`

By all means add your device. However, you are currently getting 0xffffff in response to the read ID command, which means that something is not working correctly with the communications, and until this is resolved it is impossible to debug further.

**Comment by bhura112** [comment]
check this output:
  i checked all hardware connections everthing is fine but if serial flash chip faced any communication problem then 0x9f c0mmand not write or read in correctly.
![out2](https://user-images.githubusercontent.com/16154752/30899265-d49c3a00-a37c-11e7-9e29-c9b00402e18b.png)

**Comment by bhura112** [comment]
Hello , 
I am Debug my hardware , now it's working and return id 0x012018.
when i take a firmware backup with command ./rtd -d 1 -b bck.bin program stuck on flash status : 0x00

**Comment by bhura112** [comment]
Hello Sir ,
           I am write my simple program to RTD2660 
           __sfr __at (0x90) P1;
         
         int main()
         {
           P1 = 0x00;
           while(1);
        }

but i don't know why P1 port 
![untitled](https://user-images.githubusercontent.com/16154752/31162577-e98a1f84-a8fb-11e7-9799-948d9accfc78.png)
always high

**Comment by bhura112** [comment]
Thank you so much sir for your help.
I appreciate.
Today I am successfully write and run my program .

**Comment by static-void** [comment]
Well done! What was the problem? I'm sorry I've been unable to assist over the last week or so as I have not had time, but I have intended to get back to you. If you have any improvements for the code pease submit a pull request and I'll review and merge.

**Comment by bhura112** [comment]
Hello ,
         Programmer Code is ok. No problem with this code ,my hardware connections are not correct so i get this error.
                   But Sir i have some problem with rtd2660 firmware code can you pleae help me?

**Comment by static-void** [comment]
Glad everything is working for you.

I'm afraid I haven't done any development with the firmware code. All I have done is to set up Keil and compile the firmware, without making any changes to it, so I can't help you there.
