### ISSUE TITLE
Device Macronix 0xC22013 not supported 

### ISSUE THREAD

**Issue by bgiraut** [static-void/rtd266x_programmer#3]
I have just received a PCB800099 v9 board that use an unsupported SPI chip from Macronix.
After read documentation it is look like it is a WindBond W25X40 clone.  I have made small modification in the source code and be able to read et flash the chip on the board.  May be you can update your source to accept the chip. 

Definition of the device :

{"MX25L4005"  , 0xC22013,     1024,       256, 64}

Change the mehtod SetupChipCommands to accept Macronix manufacturer via jedec_id C2

Any way, thx a lot for your programmer, it held my a lot.

**Comment by static-void** [comment]
Thanks for the report, I've added your device

**Comment by bgiraut** [comment]
I will plug the LCD tonight on the board to confirm everything is ok.

Le mar. 23 oct. 2018 à 14:46, Bernard Black <notifications@github.com> a
écrit :

**Comment by static-void** [comment]
Sorry, I forgot to add the manufacturer ID. Is that what you were expecting? https://github.com/static-void/rtd266x_programmer/commit/dfa9e743606e3ea21e5237ee8153fba7e884261f

**Comment by static-void** [comment]
I might need to check the datasheet has the same write commands... I'll have a look

**Comment by bgiraut** [comment]
Device definition is missing and SetupChipCommands  only accept WindBond manufacturer even if other manufacturer and device are definied

**Comment by static-void** [comment]
Yeah I've had a quick look at the datasheet for the Macronix part and this needs a bit more thought I think. certainly the macronix at least does not support the non-volatile status register command (0x50) and I think that implies that other modifications are needed too. I will try to investigate properly later on.

**Comment by bgiraut** [comment]
I confirme, the flash was a success !!! The board drive my LCD without any problem. Command 0x50 dont seem to be necessary to flash the firmware. 

Thx a lot.
